---
- name: Configure Nginx with Free SSL
  hosts: webserver
  become: true
  gather_facts: true

  tasks:
    - name: Print Ansible Facts
      debug:
        var: ansible_facts

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Certbot
      apt:
        name: certbot
        state: present

    - name: Install Certbot Nginx plugin
      apt:
        name: python3-certbot-nginx
        state: present

    - name: Check if Certbot is installed
      command: "certbot --version"
      register: certbot_version
      ignore_errors: true

    - name: Install Certbot if not installed
      package:
        name: certbot
        state: present
      when: "'Error' in certbot_version.stderr or 'not found' in certbot_version.stderr"

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload Nginx

    - name: Obtain SSL certificate using Certbot
      shell: "sudo certbot certonly --standalone -d shopnoww.myvnc.com --staple-ocsp --non-interactive --email visheshv97@gmail.com --agree-tos"
      args:
        executable: /bin/bash
      # when: "'certbot' not in ansible_facts.packages" #ansible_distribution == 'Ubuntu'  # Adjust for other distributions

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded